name: Elixir

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.18.4-slim

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y ca-certificates make build-essential

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test
